apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
  namespace: forum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
      - name: forum
        image: forum_project:latest  # Updated to your local image name
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: "mongodb://host.docker.internal:27017/forum"
