apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
  namespace: forum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
      - name: forum
        image: e71ea9d46954d8f6dbed5cd6410ae5f4aff876c45191665200ec67603025c10f
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "mongodb://host.docker.internal:27017/forum"  # Update as needed
        resources:
          requests:
            memory: "256Mi"  # Minimum memory requested
            cpu: "500m"      # Minimum CPU requested
          limits:
            memory: "512Mi"  # Maximum memory allowed
            cpu: "1"         # Maximum CPU allowed
